import type { Metadata } from "next";
import { VT323 } from "next/font/google";
import "./globals.css";

const terminalFont = VT323({
  weight: "400",
  variable: "--font-terminal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Coffee Shop",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${terminalFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
